api = "0.9"

[buildpack]
  id = "pimhuisman/conanpack"
  name = "Conan Buildpack"
  version = "0.1.0"

[[targets]]
  os = "darwin"

[[targets]]
  os = "freebsd"

[[targets]]
  os = "linux"

[[targets]]
  os = "openbsd"

[[stacks]]
  id = "com.github.pimhuisman.stacks.hera"
