name: Build
on:
  push:
    paths-ignore: ['**.md', '.gitignore', 'LICENSE']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up pack
        uses: buildpacks/github-actions/setup-pack@v5

      - name: Compute metadata
        id: metadata
        uses: buildpacks/github-actions/buildpack/compute-metadata@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Package ${{ steps.metadata.outputs.id }}:${{ steps.metadata.outputs.version }}
        run: pack buildpack package ${{ steps.metadata.outputs.id }}:${{ steps.metadata.outputs.version }} --config ./package.toml

      - name: Push the buildpack to Docker hub
        run: docker push ${{ steps.metadata.outputs.id }}:${{ steps.metadata.outputs.version }}
