name: Build
on:
  push:
    paths-ignore: ['**.md', '.gitignore', 'LICENSE']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up pack
        uses: buildpacks/github-actions/setup-pack@v5.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Package the buildpack
        run: pack buildpack package ${{ vars.DOCKER_NAMESPACE }}/conanpack --config ./package.toml

      - name: Register the buildpack
        run: pack buildpack register ${{ vars.DOCKER_NAMESPACE }}/conanpack
