name: Build
on:
  push:
    paths-ignore: ['**.md', '.gitignore', 'LICENSE']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Package the buildpack
        run: pack buildpack package pimhuisman/conanpack --config ./package.toml

      - name: Register the buildpack
        run: pack buildpack register pimhuisman/conanpack
